name: smapp-twitter-admin
dependencies:
- python=2.7.11
- matplotlib
- numpy
- pandas
- scipy
- gunicorn
- pip
- pip:
   - Flask==0.10.1
   - Flask-OAuthlib==0.5.0
   - Flask-Principal==0.4.0
   - Flask-WTF==0.9.5
   - Jinja2==2.7.3
   - MarkupSafe==0.23
   - PyYAML==3.11
   - WTForms==1.0.5
   - Werkzeug==0.9.6
   - backports.ssl-match-hostname==3.4.0.2
   - blinker==1.3
   - certifi==14.05.14
   - httplib2==0.9
   - ipython==2.1.0
   - itsdangerous==0.24
   - nose==1.3.3
   - oauth2==1.5.211
   - oauthlib==0.6.3
   - pymongo==3.2.1
   - python-dateutil==2.2
   - seaborn==0.3.1
   - smapp-toolkit==0.1.12
   - smappPy==0.1.8
   - tornado==4.0
   - wsgiref==0.1.2
